package com.vertexnet.realestatenet.model.bean;

// Generated Jun 16, 2012 3:57:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name = "application", catalog = "real_estate_net")
public class Application implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int customerId;
	private Customer customer;
	private byte[] application;

	public Application() {
	}

	public Application(Customer customer, byte[] application) {
		this.customer = customer;
		this.application = application;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "customer"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "customer_id", unique = true, nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "application", nullable = false)
	public byte[] getApplication() {
		return this.application;
	}

	public void setApplication(byte[] application) {
		this.application = application;
	}

}
