package com.vertexnet.realestatenet.model.bean;

// Generated May 22, 2012 8:11:57 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * SecurityQuestion generated by hbm2java
 */
@Entity
@Table(name = "security_question", catalog = "real_estate_net")
public class SecurityQuestion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int questionId;
	private String question;

	public SecurityQuestion() {
	}

	public SecurityQuestion(int questionId, String question) {
		this.questionId = questionId;
		this.question = question;
	}

	@Id
	@Column(name = "question_id", unique = true, nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	@Column(name = "question", nullable = false, length = 25)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsBuilder.reflectionEquals(this, obj);
	}

	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}
}
