/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vertexnet.realestate.view.utility;

import java.text.NumberFormat;


/**
 *
 * @author Srivathsa
 */
public class MonthYearChooserPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	/**
     * Creates new form MonthYearChooserPanel
     */
    public MonthYearChooserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monthLabel = new javax.swing.JLabel();
        monthTextField = new javax.swing.JFormattedTextField(NumberFormat.getInstance());
        yearLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JFormattedTextField(NumberFormat.getInstance());

        setBackground(new java.awt.Color(250, 250, 250));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        monthLabel.setText("Month : ");
        add(monthLabel);

        monthTextField.setColumns(5);
        add(monthTextField);

        yearLabel.setText("Year : ");
        add(yearLabel);

        yearTextField.setColumns(5);
        add(yearTextField);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel monthLabel;
    private javax.swing.JFormattedTextField monthTextField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JFormattedTextField yearTextField;
    // End of variables declaration//GEN-END:variables
    
	public javax.swing.JTextField getMonthTextField() {
		return monthTextField;
	}

	public javax.swing.JTextField getYearTextField() {
		return yearTextField;
	}

	public javax.swing.JLabel getMonthLabel() {
		return monthLabel;
	}

	public javax.swing.JLabel getYearLabel() {
		return yearLabel;
	}
}
